// TODO fix type issues
// @ts-nocheck

import {
  Box,
  Button,
  Icon,
  Text,
  useTheme,
  useColorModeValue,
} from '@interchain-ui/react';

const stacks = ['Cosmos Kit', 'Next.js'];

export function Header() {
  const { theme, setTheme } = useTheme();

  const toggleColorMode = () => {
    setTheme(theme === 'light' ? 'dark' : 'light');
  };

  return (
    <>
      <Box display="flex" justifyContent="end" mb="$8">
        <Button
          intent="secondary"
          size="sm"
          attributes={{
            paddingX: 0,
          }}
          onClick={toggleColorMode}
        >
          <Icon name={useColorModeValue('moonLine', 'sunLine')} />
        </Button>
      </Box>

      <Box textAlign="center">
        <Text
          as="h1"
          fontWeight="$extrabold"
          fontSize={{ mobile: '$6xl', tablet: '$10xl' }}
          attributes={{
            marginBottom: '$2',
          }}
        >
          Informal Systems Tech Task: Proposals
        </Text>
        <Text as="h3" fontWeight="$bold">
          <Text
            as="span"
            fontSize={{ mobile: '$3xl', tablet: '$8xl', desktop: '$8xl' }}
          >
            Generated by&nbsp;
          </Text>
          <Text
            as="a"
            fontSize={{ mobile: '$3xl', tablet: '$8xl', desktop: '$8xl' }}
            color={useColorModeValue('$primary500', '$primary200')}
            attributes={{
              href: 'https://github.com/hyperweb-io/create-cosmos-app',
              target: '_blank',
              rel: 'noopener noreferrer',
              textDecoration: 'none'
            }}
          >
            Create Cosmos App
          </Text>
        </Text>
        <Text as="h3" fontWeight="$bold">
          <Text
            as="span"
            fontSize={{ mobile: '$3xl', tablet: '$8xl', desktop: '$8xl' }}
            attributes={{ marginLeft: '8px',  }}
          >
            Modified by&nbsp;
          </Text>
          <Text
            as="a"
            fontSize={{ mobile: '$3xl', tablet: '$8xl', desktop: '$8xl' }}
            color={useColorModeValue('$primary500', '$primary200')}
            attributes={{
              href: 'https://github.com/rh0delta',
              target: 'blank',
              rel: 'noopener noreferrer',
              textDecoration: 'none'
            }}
          >
            Me
          </Text>
        </Text>
      </Box>
    </>
  );
}
