import Head from 'next/head';
import { Container } from '@interchain-ui/react';
import { Header } from './Header';
import { Footer } from './Footer';

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <Container maxWidth="64rem" attributes={{ py: '$14' }}>
      <Head>
        <title>Informal Systems Tech Task: Proposals</title>
        <meta name="description" content="Generated by create cosmos app; Modified by me" />
        <link rel="icon" href="/image/favicon.ico" />
      </Head>
       {/* @ts-ignore */}
      <Header />
      {children}
       {/* @ts-ignore */}
      <Footer />
    </Container>
  );
}
